"""
Application monitoring and metrics.
"""
from prometheus_client import Counter, Histogram, Gauge, generate_latest, CONTENT_TYPE_LATEST
from fastapi import Response
import time


# Metrics
request_count = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status"]
)

request_duration = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "endpoint"]
)

active_sessions = Gauge(
    "active_test_sessions",
    "Number of active test sessions"
)

questions_generated = Counter(
    "questions_generated_total",
    "Total questions generated by LLM"
)

reviews_completed = Counter(
    "reviews_completed_total",
    "Total reviews completed"
)


def track_request(method: str, endpoint: str, status_code: int, duration: float):
    """Track an HTTP request."""
    request_count.labels(method=method, endpoint=endpoint, status=status_code).inc()
    request_duration.labels(method=method, endpoint=endpoint).observe(duration)


async def get_metrics():
    """Get Prometheus metrics."""
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)
